=== garciatomeabelxose/Stem/Lenguaje de marcas/UD1/Estudio1/Estudio3.dtd
<!ELEMENT ligaDeCohetes (grupo)>
<!ELEMENT grupo (jugadores)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (coche,dinero,pass)>
<!ELEMENT coche (tipo,color)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT dinero (#PCDATA)>
<!ELEMENT pass (#PCDATA)>

=== garciatomeabelxose/Stem/Lenguaje de marcas/Estudio1/Estudio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaDeCohetes SYSTEM "estudio3.dtd">
<ligaDeCohetes>
    <grupo>
        <jugadores>
            <jugador>
                <coche>
                    <tipo>deportivo</tipo>
                    <color>rojo</color>
                </coche>
                <dinero></dinero>
                <pass></pass>
            </jugador>
        </jugadores>
    </grupo>
</ligaDeCohetes>
